# Generated by Django 3.2.8 on 2022-05-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Graph',
                'verbose_name_plural': 'Graphs',
            },
        ),
        migrations.CreateModel(
            name='GraphNodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.graph')),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.node')),
            ],
            options={
                'verbose_name': 'Graph-Node Relation',
                'verbose_name_plural': 'Graph-Node Relations',
                'unique_together': {('graph_id', 'node_id')},
            },
        ),
    ]
