# Generated by Django 3.2.8 on 2022-05-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1)),
                ('target', models.CharField(max_length=1)),
                ('distance', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
