# Generated by Django 3.2.8 on 2022-09-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['source'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set(),
        ),
    ]
