# Generated by Django 3.2.8 on 2022-09-13 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_delete_graphnoderelation'),
        ('node', '0002_auto_20220912_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['graph_id', 'source'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AddField(
            model_name='node',
            name='graph_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='graph.graph'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('graph_id', 'source', 'target')},
        ),
    ]
