# Generated by Django 3.2.8 on 2022-09-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20220912_2222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='node',
            table='node',
        ),
    ]
