# Generated by Django 3.2.8 on 2022-09-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_node_graph_id_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='node',
            name='target',
            field=models.CharField(max_length=30),
        ),
    ]
