# Generated by Django 3.2.8 on 2022-09-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_graph_description'),
        ('node', '0006_auto_20220919_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='graph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.graph'),
        ),
    ]
